FROM node:20-alpine

WORKDIR /app/frontend

# Copy package files
COPY frontend/package.json ./
COPY frontend/package-lock.json ./

# Install dependencies
RUN npm ci

# Copy application code
COPY frontend ./

EXPOSE 3000

CMD ["npm", "run", "dev"]
