FROM node:20-alpine

WORKDIR /app/frontend

# Copy package file
COPY frontend/package.json ./

# Install dependencies
RUN npm install --legacy-peer-deps

# Copy application code
COPY frontend ./

EXPOSE 3000

CMD ["npm", "run", "dev"]
